services:
  service-cluster:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - iaas-firecracker-network

networks:
  iaas-firecracker-network:
    external: true
    name: service-config_iaas-firecracker-network
